import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
const inter = Inter({ subsets: ["latin"] });
import SideBar from "@/components/Header";
import StoreProvider from "./StoreProvider";
import './globals.css'
// import "@fortawesome/fontawesome-svg-core/styles.css";
// import { config } from "@fortawesome/fontawesome-svg-core";
// config.autoAddCss = false;


export const metadata: Metadata = {
  title: "Navy Film",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <StoreProvider>
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <div>

        {children}
      </div>
      </body>
    </html>
  </StoreProvider>
  );
}


